import "@t007/utils";
import type { FieldOptions } from "@t007/input";

/** Shared options for alert, confirm, and prompt dialogs. */
export interface DialogOptions {
  /** Unique identifier for the dialog for programmatic dismissal. Auto-generated by default. */
  id?: string;
  /** Text for the confirmation button. Defaults to "OK". */
  confirmText?: string;
  /** Text for the cancel button where applicable. Defaults to "Cancel". */
  cancelText?: string;
  /** Browser behavior for handling dialog closure. Defaults to "any". */
  closedBy?: HTMLDialogElement["closedBy"];
  /** Render dialog inside a specific root element instead of document body. */
  rootElement?: HTMLElement;
  /** Whether to restrict interactions to `rootElement` if provided. Defaults to `true`. */
  scoped?: boolean;
}

// BUNDLE EXPORTS & GLOBAL DECLARATIONS

/** Show an alert dialog and resolve when the user confirms.
 * @param message Message shown in the dialog body.
 * @param options Optional dialog configuration.
 * @returns Promise that resolves to the user choice.
 */
export function alert(message: string, options?: DialogOptions): Promise<boolean>;
/** Show a confirm dialog and resolve with the user choice.
 * @param question Question shown in the dialog body.
 * @param options Optional dialog configuration.
 * @returns Promise that resolves to true when confirmed.
 */
export function confirm(question: string, options?: DialogOptions): Promise<boolean>;
/** Show a prompt dialog and resolve with the entered value.
 * @param question Question shown in the dialog body.
 * @param defaultValue Initial value for the prompt input.
 * @param options Optional dialog configuration.
 * @returns Promise that resolves to the entered string or null.
 */
export function prompt(question: string, defaultValue?: string, options?: DialogOptions & FieldOptions): Promise<string | null>;
/** Dismiss a dialog by id or all dialogs when no id is provided.
 * @param id Optional unique identifier of the dialog to dismiss. If not provided, all dialogs will be dismissed.
 * @param response Optional value to resolve the dialog's promise with. If not provided, defaults to `true` for confirm and alert dialogs, and `null` for prompt dialogs.
 */
export function dismiss(id?: string, response?: any): void;

declare global {
  interface T007Namespace {
    /** Browser alert helper. */
    alert: typeof Alert;
    /** Browser confirm helper. */
    confirm: typeof Confirm;
    /** Browser prompt helper. */
    prompt: typeof Prompt;
    /** Dismisses a dialog by id or all dialogs when no id is provided. */
    dismiss: (id?: string, res?: any) => void;
  }
  interface Window {
    Alert?: T007Namespace["alert"];
    Confirm?: T007Namespace["confirm"];
    Prompt?: T007Namespace["prompt"];
    Dismiss?: T007Namespace["dismiss"];
  }
}
